### ISSUE TITLE
Quality of Life Improvements

### ISSUE THREAD

**Issue by jbowen93** [30x/khaos-monkey#9]
Ideally Khaos Monkey wouldn't run outside of working hours.

In my mind that means:

- Monday through Friday 9am to 5pm. Lets go PST for now but maybe the option for an env var?
- Not on weekends.
- Not on holidays.

There's obviously a lot of variables here but I think a starting point could be just grabbing a list of Google's US holidays and getting the M-F 9-5 working. 

Future improvements could include:

- Setting Time Zone via Env Var
- Custom Holidays passed through a calendar
- Similar to the above but a fully configurable schedule, hopefully settable via Google Calendar, obviously this brings in complexity as we now need to auth to that calendar but just an idea. In the interim we could try to come up with some kind of sane format that could be accomplished with a config map.

**Comment by noahdietz** [comment]
Yeah, you're right, consideration for time of day and working hours is necessary.

How much of this do you think we need to implement as configuration in the application and how much belongs in the manifest for a [ScheduledJob](http://kubernetes.io/docs/user-guide/scheduled-jobs/)? I think the job manifest gives you a frequency, which day, time of day, but obviously not holidays, according to the [Cron convention](https://en.wikipedia.org/wiki/Cron).

**Comment by jbowen93** [comment]
Ya unfortunately it's not clear to me if it's better to run this as a job or as a long lived pod...I'll read more into scheduled jobs and get back to this.

**Comment by noahdietz** [comment]
I think your idea of running it as a long lived pod gives us the ability to have it run at _random times_ throughout the day...where as a ScheduledJob is just that, _scheduled_, so we know when itll happen and its not fun that way

**Comment by noahdietz** [comment]
Example `CronJob` for `khaos-monkey` that runs _Every Wednesday @ 1:30pm_ (per [Cron convention](https://en.wikipedia.org/wiki/Cron))
runs for 10m w/an event every 30sec, that only kills random pods (as configured by the `khaos-monkey` env vars)
```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: khaos-monkey
spec:
  schedule: "30 13 * * 4" # every Wednesday at 1:30 pm
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: khaos-monkey
            image: noahdietz/khaos-monkey:dev
            env:
            - name: KHAOS_INTERVAL
              value: "30s"
            - name: KHAOS_DURATION
              value: "10m"
            - name: KHAOTIC_EVENTS
              value: "kill-pods"
            - name: KHAOS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KHAOS_MONKEY_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          restartPolicy: OnFailure
```
